/* All artwork uses the supplied IP expression sheets, rendered locally. */
'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const palette=['#58bbd1','#f49cc2','#ffd554'];
const sourceRects=[[[100,174,209,260],[1265,165,215,266],[693,695,205,260]],[[1335,842,176,142],[1095,198,177,140],[865,414,174,140],[1330,632,183,145]],[[904,160,222,215],[1700,144,229,233],[649,402,222,218],[390,680,225,216]]];
const referenceSizes=[[1933,1280],[1920,1296],[2048,986]],sprites=[[],[],[]];
let demo=null,demoNote='',demoSlowFrame=0;
let state='menu',game=new IdiotGame.Game(),keys={},acc=0,last=0,particles=[],floaters=[],toastTimer=0,sound=true,audioCtx=null,progress={completed:[],best:{}},endlessSeed=1,shake=0;
try{progress=Object.assign(progress,JSON.parse(localStorage.getItem('three-idiots-v1')||'{}'));}catch{}
if(progress.chapterRevision!==2){progress.completed=progress.completed.filter(i=>i<3);for(let i=3;i<=8;i++)delete progress.best[i];progress.chapterRevision=2;}
function save(){try{localStorage.setItem('three-idiots-v1',JSON.stringify(progress));}catch{}}
function tone(type){if(!sound)return;try{audioCtx ||=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);const f={jump:330,bounce:170,button:540,bridge:660,fall:140,trap:90,arrive:880,win:1046,portal:740,achievement:990}[type]||400;osc.type=type==='trap'?'sawtooth':'sine';osc.frequency.setValueAtTime(f,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='fall'?50:f*1.6,audioCtx.currentTime+.13);gain.gain.setValueAtTime(.035,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.22);osc.start();osc.stop(audioCtx.currentTime+.23);}catch{}}
function toast(t){if(!t)return;$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
function rounded(x,y,w,h,r=8,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function text(t,x,y,size=14,color='#70795e',align='left',weight=500){ctx.font=`${weight} ${size}px "Noto Sans SC","Microsoft YaHei",sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(t,x,y);}
function line(x1,y1,x2,y2,color='#c0c8ad',width=2,dash=[]){ctx.beginPath();ctx.setLineDash(dash);ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();ctx.setLineDash([]);}
function sprite(context,id,emotion,x,y,w,h,rotation=0){const image=sprites[id][emotion]||sprites[id][0];context.save();context.translate(x+w/2,y+h/2);context.rotate(rotation);if(image){const scale=Math.min(w/image.width,h/image.height);context.drawImage(image,-image.width*scale/2,-image.height*scale/2,image.width*scale,image.height*scale);}else{context.fillStyle=palette[id];context.beginPath();context.roundRect(-w/2,-h/2,w,h,id===0?6:20);context.fill();context.fillStyle='#344435';context.fillRect(-10,-4,6,2);context.fillRect(5,-4,6,2);}context.restore();}
let loaded=0;
['blue','pink','star'].forEach((name,id)=>{const img=new Image();img.onload=()=>{const [rw,rh]=referenceSizes[id];for(const r of sourceRects[id]){const s=document.createElement('canvas');s.width=Math.ceil(r[2]);s.height=Math.ceil(r[3]);let c=s.getContext('2d',{willReadFrequently:true});c.drawImage(img,r[0]*img.width/rw,r[1]*img.height/rh,r[2]*img.width/rw,r[3]*img.height/rh,0,0,s.width,s.height);try{const pixels=c.getImageData(0,0,s.width,s.height);for(let i=0;i<pixels.data.length;i+=4){const min=Math.min(pixels.data[i],pixels.data[i+1],pixels.data[i+2]);if(min>245)pixels.data[i+3]=0;else if(min>230)pixels.data[i+3]=Math.round((245-min)/15*255);}c.putImageData(pixels,0,0);}catch{/* file:// may taint canvases; original white sheet remains usable. */}sprites[id].push(s);}loaded++;drawPortraits();};img.onerror=()=>toast('角色素材加载失败，请保留 assets 文件夹。');img.src=`assets/${name}.png`;});
function drawPortraits(){document.querySelectorAll('[data-portrait]').forEach(c=>{const cc=c.getContext('2d');cc.clearRect(0,0,c.width,c.height);sprite(cc,+c.dataset.portrait,0,6,8,c.width-12,c.height-16);});}
function burst(x,y,color,n=20){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*7,vy:-Math.random()*7-1,life:50+Math.random()*30,color});}
function switchTo(i){if(demo)takeover();game.select(i);updateCards();canvas.focus({preventScroll:true});}
function updateCards(){document.querySelectorAll('[data-select]').forEach(b=>{const id=+b.dataset.select;b.classList.toggle('selected',id===game.selected);b.setAttribute('aria-pressed',id===game.selected?'true':'false');b.style.opacity=game.people[id].arrived?'.5':'1';});}
function start(index=0,seed=1){clearTimeout(toastTimer);$('toast').classList.remove('show');demo=null;demoNote='';$('demoBanner').classList.add('hidden');game=new IdiotGame.Game(index,seed);state='play';keys={};particles=[];floaters=[];acc=0;['startScreen','winScreen','pauseScreen'].forEach(id=>$(id).classList.add('hidden'));$('levelNo').textContent=index>=8?'∞':String(index+1).padStart(2,'0');$('levelTitle').textContent=game.level.name;$('modeLabel').textContent=index>=8?'程序随机挑战 · 种子 '+seed:['第一章 · 出门就不容易','第一章 · 出门就不容易','第二章 · 队友也是道具','第二章 · 队友也是道具','第三章 · 凑合着合作','第三章 · 凑合着合作','第四章 · 信任危机','最终章 · 谁也不许落下'][index];updateCards();canvas.focus({preventScroll:true});tone('button');}
function pause(value){if(value&&state==='play'){state='paused';keys={};$('pauseScreen').classList.remove('hidden');}else if(!value&&state==='paused'){state='play';$('pauseScreen').classList.add('hidden');canvas.focus({preventScroll:true});}}
function win(){state='win';$('demoBanner').classList.add('hidden');const secs=Math.round(game.frames/60);if(!game.wasDemo&&game.level.index<8&&!progress.completed.includes(game.level.index))progress.completed.push(game.level.index);const prev=progress.best[game.level.index];if(!game.wasDemo&&(!prev||secs<prev))progress.best[game.level.index]=secs;save();$('winTitle').textContent=game.level.index===7?'三个大聪明，一个都没少。':'居然一个都没少！';$('winText').textContent=`用时 ${Math.floor(secs/60)} 分 ${secs%60} 秒 · 摔了 ${game.deaths} 次 · 友情暂时还在`;$('nextBtn').textContent=game.level.index===7?'进入无尽大聪明模式 →':'下一个坑 →';if(game.wasDemo){$('winTitle').textContent='高玩下班，轮到你了。';$('winText').textContent='完整路线已经演示 · 演示不计入通关记录';$('replayBtn').textContent='我来挑战这一关';}else $('replayBtn').textContent='再来一次';$('winScreen').classList.remove('hidden');burst(600,180,'#c6dc77',65);}
function processEvents(){for(const e of game.events){tone(e.type);if(e.text)toast(e.text);if(['bounce','trap','fall'].includes(e.type)){shake=e.type==='trap'?13:4;const p=game.people[game.selected];floaters.push({text:e.type==='bounce'?'DUANG!':e.type==='trap'?'啊？！':'……',x:p.x,y:p.y-25,life:65});burst(p.x,p.y,palette[p.id],12);}if(e.type==='bridge')burst(600,490,'#c1d780',35);if(e.type==='win')win();}game.events=[];}
function background(){ctx.fillStyle='#f9f8ef';ctx.fillRect(0,0,1200,650);ctx.fillStyle='#e4e6d8';for(let x=20;x<1200;x+=28)for(let y=20;y<650;y+=28){ctx.beginPath();ctx.arc(x,y,.75,0,7);ctx.fill();}ctx.fillStyle='#eff0e2';ctx.beginPath();ctx.arc(1045,350,245,Math.PI,0);ctx.lineTo(1290,650);ctx.lineTo(800,650);ctx.fill();ctx.fillStyle='#f0f0e3';ctx.beginPath();ctx.arc(190,400,170,Math.PI,0);ctx.lineTo(360,650);ctx.lineTo(20,650);ctx.fill();
 text('一起走，才算过关。',60,68,14,'#a0a58e');text('EXIT IS A TEAM SPORT',60,89,8,'#acb19d');
 // Hand-drawn clouds and decorative plants.
 for(const [x,y,s] of [[530,115,1],[1020,110,.7],[350,205,.6]]){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.beginPath();ctx.moveTo(-45,12);ctx.bezierCurveTo(-65,-8,-30,-25,-20,-9);ctx.bezierCurveTo(-13,-48,33,-45,37,-12);ctx.bezierCurveTo(67,-21,79,17,50,18);ctx.lineTo(-45,18);ctx.fillStyle='#fdfcf7';ctx.fill();ctx.strokeStyle='#d9ddca';ctx.lineWidth=1.5;ctx.stroke();ctx.restore();}}
function terrain(s){rounded(s.x,s.y,s.w,s.h,5,'#e3e7d2','#7f8e6c');ctx.fillStyle='#c7d79f';ctx.fillRect(s.x+1,s.y+1,s.w-2,9);line(s.x+2,s.y+11,s.x+s.w-2,s.y+11,'#a6b68c',1);ctx.save();ctx.beginPath();ctx.rect(s.x,s.y+12,s.w,s.h-12);ctx.clip();for(let x=s.x-50;x<s.x+s.w+70;x+=24)line(x,s.y+16,x-55,s.y+100,'#d2d8be',1);ctx.restore();}
function pad(p,color,label,on){rounded(p.x-5,p.y-7,p.w+10,10,3,'#59634e');rounded(p.x,p.y-(on?9:15),p.w,on?5:11,3,on?'#c0db80':color,'#59634e');if(label)text(label,p.x+p.w/2,p.y-28,11,on?'#81a05b':'#89927b','center',600);if(on){ctx.fillStyle='#b2ce7b';ctx.beginPath();ctx.arc(p.x+p.w/2,p.y-45,3,0,7);ctx.fill();}}
function arrow(x,y,rotation=0){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);line(-18,0,18,0,'#a4ae8d',2,[5,5]);line(10,-6,18,0,'#a4ae8d',2);line(10,6,18,0,'#a4ae8d',2);ctx.restore();}
function draw(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.9;if(shake<.2)shake=0;}background();const l=game.level;
 if(l.custom){drawAdvanced(game);}else{
 // Mechanism connection lines make the dependencies visible.
 if(!l.seesaw){line(l.blue.x+27,l.blue.y-4,l.blue.x+27,566,'#a6c7c5',2,[5,5]);line(l.blue.x+27,566,l.gate.x+11,566,'#a6c7c5',2,[5,5]);line(l.gate.x+11,566,l.gate.x+11,520,'#a6c7c5',2,[5,5]);}
 for(const s of l.platforms)terrain(s);
 // The pit has friendly, clearly visible teeth.
 ctx.fillStyle='#ede5d8';ctx.fillRect(l.gapL+1,610,l.gapR-l.gapL-2,40);for(let x=l.gapL+8;x<l.gapR-10;x+=24){ctx.beginPath();ctx.moveTo(x,630);ctx.lineTo(x+10,607);ctx.lineTo(x+20,630);ctx.fillStyle='#c5b8a5';ctx.fill();ctx.strokeStyle='#aa9b8a';ctx.lineWidth=1.5;ctx.stroke();}text('这里不太适合散步', (l.gapL+l.gapR)/2,588,11,'#b3ac99','center');
 if(game.bridge){terrain({x:l.gapL,y:520,w:l.finale?140:l.gapR-l.gapL,h:18});if(l.finale&&game.finalBridge)terrain({x:l.gapL+140,y:520,w:l.gapR-l.gapL-140,h:18});}else{line(l.gapL,525,l.gapR,525,'#b2bea0',2,[7,7]);text('等待接应',600,550,10,'#9aa58b','center');}
 const weighted=game.onPad(game.people[0],l.blue);pad(l.blue,palette[0],l.seesaw?'跳起 → 重砸':'01 · 重量感应',l.seesaw?game.frames-game.flags.slam<25:weighted);pad(l.pink,palette[1],'02 · 弹滚接应',game.pinkOn);pad(l.yellow,palette[2],'03 · 高空接力',game.bridge);
 if(l.finale&&game.bridge){pad({x:980,y:520,w:48},palette[1],'04 · 留在这里',game.onPad(game.people[1],{x:980,y:520,w:48})||game.finalBridge);pad({x:535,y:520,w:48},palette[0],'05 · 最后一脚',game.finalBridge);}
 if(l.trap){pad(l.trap,'#e7806e',l.n===6?'捷径！':'千万别碰',false);text('!',l.trap.x+l.trap.w/2,452,18,'#c78470','center',800);}
 // Gate hangs from a small lintel.
 if(!l.seesaw){rounded(l.gate.x-9,339,40,14,4,'#8e9b7b','#59684d');if(!game.gateOpen){rounded(l.gate.x,352,l.gate.w,168,3,'#d1d9bf','#77846a');for(let y=365;y<510;y+=18)line(l.gate.x+4,y,l.gate.x+18,y-10,'#94a283',2);text('等一下',l.gate.x+11,326,11,'#8f977f','center');}else{rounded(l.gate.x,352,l.gate.w,22,3,'#d0e5a5','#77846a');text('请通过',l.gate.x+11,326,11,'#7f9e61','center');}
 }
 // Spring / seesaw.
 if(!l.seesaw){
 const sx=l.spring.x;rounded(sx-3,510,44,10,3,'#75825f');ctx.beginPath();ctx.moveTo(sx+5,510);for(let j=0;j<5;j++)ctx.lineTo(sx+(j%2?6:30),507-j*5);ctx.strokeStyle='#79876a';ctx.lineWidth=3;ctx.stroke();rounded(sx-4,479,47,9,3,'#f0b9cc','#806b74');text(l.seesaw?'重量弹射':'弹力起飞',sx+18,463,10,'#a58691','center');if(l.seesaw){line(sx-38,501,sx+45,475,'#a88965',7);ctx.beginPath();ctx.moveTo(sx-5,518);ctx.lineTo(sx+5,497);ctx.lineTo(sx+15,518);ctx.fillStyle='#c7af84';ctx.fill();}
 arrow(510,410,-.5);
 // Fan / lift stream.
 rounded(l.fan.x,501,l.fan.w,19,5,'#a5b6aa','#5e766a');const fx=l.fan.x+l.fan.w/2;ctx.save();ctx.translate(fx,504);ctx.rotate(game.pinkOn?performance.now()/90:0);for(let a=0;a<4;a++){ctx.rotate(Math.PI/2);rounded(-3,2,6,18,3,'#698875');}ctx.restore();if(game.pinkOn){for(let i=0;i<8;i++){const yy=480-((performance.now()/6+i*39)%240);line(fx-18+(i%3)*18,yy,fx-18+(i%3)*18,yy-24,'#bdd5ba',2);}arrow(fx,275,-Math.PI/2);}text(game.pinkOn?'乘风上去 ↑':'接应后启动',fx,547,10,'#8d9d88','center');
 }else{
 const hit=Math.max(0,1-(game.frames-(game.flags.slam||-100))/35);
 line(303,505+hit*10,455,505-hit*20,'#796e58',9);
 ctx.beginPath();ctx.moveTo(365,520);ctx.lineTo(382,495);ctx.lineTo(399,520);ctx.closePath();ctx.fillStyle='#bba881';ctx.fill();
 const waiting=game.people.some(p=>p.id!==0&&p.grounded&&game.onPad(p,l.seat));
 pad(l.seat,palette[1],waiting?'已就位 · 等待重砸':'乘客在此停稳',waiting);
 text('站着不算，跳下来才算！',320,410,15,'#698293','center',700);
 text('两次发射 · 两座高台 · 一起回家',600,130,18,'#7d876c','center',700);
 ctx.beginPath();ctx.setLineDash([7,8]);ctx.moveTo(438,465);ctx.quadraticCurveTo(600,65,822,316);ctx.strokeStyle='#dba5bc';ctx.lineWidth=2;ctx.stroke();
 ctx.beginPath();ctx.moveTo(438,455);ctx.quadraticCurveTo(680,-40,975,255);ctx.strokeStyle='#d1bd68';ctx.stroke();ctx.setLineDash([]);
 text('第一位：秦练习',804,365,12,'#a78191','center');text('第二位：董高分',982,305,12,'#ac994d','center');
 }
 if(l.wind&&!game.pinkOn){for(let i=0;i<6;i++)arrow(510+i*35,370+(i%2)*50,Math.PI);text('逆风中，别松手',605,331,12,'#90a291','center');}
 if(l.portal){for(const px of [409,781]){ctx.beginPath();ctx.ellipse(px,476,17,34,0,0,7);ctx.strokeStyle='#b394b6';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='#e9c9e0';ctx.lineWidth=2;ctx.stroke();}text('秦练习专属',410,426,10,'#a281a2','center');}
 if(game.crate){const b=game.crate;rounded(b.x,b.y,b.w,b.h,4,'#c9ae85','#82765f');line(b.x+5,b.y+5,b.x+b.w-5,b.y+b.h-5,'#a58c64',2);line(b.x+b.w-5,b.y+5,b.x+5,b.y+b.h-5,'#a58c64',2);text('→ 推开',b.x+20,b.y-13,10,'#9b8b74','center');}
 }
 // Exit.
 const ex=l.exit.x;const ready=l.custom?AdvancedLevels.ready(game):game.bridge&&(!l.finale||game.finalBridge);rounded(ex,408,63,112,25,ready?'#dbe99e':'#e6e9d6','#727e5e');rounded(ex+9,420,45,99,20,ready?'#aac66e':'#cbd3b5');ctx.fillStyle='#5b6e40';ctx.beginPath();ctx.arc(ex+43,474,3,0,7);ctx.fill();text('EXIT',ex+32,390,13,'#6c7d52','center',800);arrow(ex+32,374,0);for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(ex+11+i*20,542,5,0,7);ctx.fillStyle=game.people[i].arrived?palette[i]:'#d6dcc8';ctx.fill();}
 // Small plants.
 for(const x of [35,175,1030,1180]){line(x,519,x,500,'#8eaa74',2);line(x,512,x-8,504,'#8eaa74',2);line(x,510,x+7,500,'#8eaa74',2);}
 for(const p of game.people){if(p.arrived){sprite(ctx,p.id,0,1094+p.id*26,560,25,35);continue;}ctx.fillStyle='#28322015';ctx.beginPath();ctx.ellipse(p.x+p.w/2,Math.min(524,p.y+p.h+5),p.w*.45,4,0,0,7);ctx.fill();let emotion=p.emotion>0?1:0;if(p.id===0&&game.bumps>=20)emotion=1;if(p.id===2&&game.pinkOn)emotion=game.bridge?3:0;sprite(ctx,p.id,emotion,p.x-4,p.y-5,p.w+8,p.h+5,p.id===1?p.rotation:0);
  if(p.id===game.selected){ctx.fillStyle=palette[p.id];ctx.beginPath();ctx.moveTo(p.x+p.w/2-6,p.y-20);ctx.lineTo(p.x+p.w/2+6,p.y-20);ctx.lineTo(p.x+p.w/2,p.y-12);ctx.fill();rounded(p.x+p.w/2-9,p.y-43,18,17,4,'#fffdf4','#acb397');text(String(p.id+1),p.x+p.w/2,p.y-30,10,'#58614b','center',800);}}
 for(const f of floaters)text(f.text,f.x,f.y,22,'#8f7359','center',900);
 for(const p of particles){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.life/5);ctx.globalAlpha=Math.min(1,p.life/20);ctx.fillStyle=p.color;ctx.fillRect(-3,-3,6,6);ctx.restore();}ctx.restore();}
function updateHUD(){const n=game.people.filter(p=>p.arrived).length;$('arrived').textContent=n;const t=Math.floor(game.frames/60);$('timer').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;$('objective').textContent=state==='menu'?'今日目标：整整齐齐地出门。':game.bridge?(game.level.finale&&!game.finalBridge?'最后接力：秦练习踩 04，艾改错踩 05。':`出口开放！还有 ${3-n} 个大聪明在路上。`):game.pinkOn?'让董高分乘风到高台，踩下黄色按钮。':game.gateOpen?'秦练习，过坑接应！艾改错先别走。':'先让艾改错站上蓝色重量按钮。';if(state!=='menu'&&game.level.custom)$('objective').textContent=AdvancedLevels.ready(game)&&game.level.custom!==4?`出口开放！还有 ${3-n} 个大聪明在路上。`:AdvancedLevels.objective(game);if(state!=='menu'&&game.level.seesaw&&!game.bridge){const ready=game.people.some(p=>p.id!==0&&p.grounded&&game.onPad(p,game.level.seat));$('objective').textContent=ready?'乘客已就位！换艾改错，在蓝板上跳起重砸。':game.pinkOn?'再把董高分送到发射座，完成第二次弹射。':'先让秦练习在粉色发射座停稳，再换艾改错重砸。';}updateCards();}
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;acc+=dt;while(acc>=1/60){if(state==='play'){if(demo){if(++demoSlowFrame%2===0){try{const result=demo.next();if(result.done){demo=null;$('demoBanner').classList.add('hidden');}else if(result.value.hold){if(demoNote!==result.value.note){demoNote=result.value.note;$('demoStep').textContent=demoNote;}}else{game.tick(result.value);processEvents();}}catch(error){takeover();toast(error.message);}}}else{game.tick({left:keys.ArrowLeft||keys.KeyA,right:keys.ArrowRight||keys.KeyD,jump:keys.Space||keys.ArrowUp||keys.KeyW});processEvents();}}if(state!=='paused'){for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.15;p.life--;}particles=particles.filter(p=>p.life>0);for(const f of floaters){f.y-=.7;f.life--;}floaters=floaters.filter(f=>f.life>0);}acc-=1/60;}draw();updateHUD();requestAnimationFrame(frame);}
document.addEventListener('keydown',e=>{if($('modal').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&state==='play')e.preventDefault();if(e.repeat){keys[e.code]=true;return;}if(e.code==='Escape'){pause(state==='play');return;}if(state!=='play')return;if(demo&&['ArrowLeft','ArrowRight','ArrowUp','KeyA','KeyD','KeyW','Space','Digit1','Digit2','Digit3','Tab'].includes(e.code))takeover();keys[e.code]=true;if(/^Digit[123]$/.test(e.code))switchTo(+e.code.slice(-1)-1);if(e.code==='Tab')switchTo((game.selected+1)%3);if(e.code==='KeyR')start(game.level.index,game.level.seed);});
document.addEventListener('keyup',e=>{keys[e.code]=false;});window.addEventListener('blur',()=>{keys={};pause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys={};pause(true);}});
document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>switchTo(+b.dataset.select));
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(demo)takeover();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>{keys[b.dataset.key]=false;};b.onlostpointercapture=()=>{keys[b.dataset.key]=false;};});
$('startBtn').onclick=()=>start(0);$('endlessBtn').onclick=()=>start(8,Math.floor(Math.random()*9999)+1);$('resetBtn').onclick=()=>{if(state!=='menu')start(game.level.index,game.level.seed);};$('pauseBtn').onclick=()=>pause(state==='play');$('resumeBtn').onclick=()=>pause(false);$('replayBtn').onclick=()=>start(game.level.index,game.level.seed);$('nextBtn').onclick=()=>{const i=game.level.index;start(i>=7?8:i+1,i>=7?++endlessSeed:1);};$('soundBtn').onclick=()=>{sound=!sound;$('soundBtn').textContent='声音：'+(sound?'开':'关');if(sound)tone('button');};
let resumeAfterModal=false;function modal(html){resumeAfterModal=state==='play';if(resumeAfterModal)pause(true);$('modalBody').innerHTML=html;$('modal').showModal();}function closeModal(){$('modal').close();} $('closeModal').onclick=closeModal;$('modal').addEventListener('close',()=>{if(resumeAfterModal)pause(false);});
$('helpBtn').onclick=()=>modal('<div class="eyebrow">IDIOTS’ FIELD GUIDE</div><h2>合作靠默契，操作靠这里。</h2><p>← → 或 A / D 移动，空格 / ↑ / W 跳跃。董高分在空中<strong>长按跳跃</strong>可以滑翔。数字 1 / 2 / 3 或点击角色卡切换角色，Tab 顺序切换。</p><p><strong>艾改错：</strong>沉、跳得低，只有他能压住蓝按钮。<br><strong>秦练习：</strong>有惯性，可以反向减速；粉按钮和弹簧只认她。队友落在她身上会弹起。<br><strong>董高分：</strong>能滑翔、乘风到高台，踩黄按钮接队友。</p><p>R 重来，Esc 暂停。掉坑会自动回到起点，已启动的接应机关保留。三个角色都进门才算过关。</p><p>手机可使用下方方向与跳跃按钮。随机模式采用预设机关模板和种子组合，无需联网。</p>');
$('hintBtn').onclick=()=>modal(`<div class="eyebrow">一点点场外援助</div><h2>${game.level.name}</h2><p>${game.level.hint}</p><p>小技巧：切走之后，角色会留在原地。秦练习有惯性，松开方向键后还会滚一小段；需要停住时，按反方向刹车。</p>`);
$('levelsBtn').onclick=()=>{modal('<div class="eyebrow">EIGHT LITTLE DISASTERS</div><h2>关卡手册</h2><p>8 次集体出逃。所有关卡都可以直接尝试。</p><div class="level-grid">'+IdiotGame.names.map((n,i)=>`<button data-level="${i}"><b>${String(i+1).padStart(2,'0')} ${progress.completed.includes(i)?'✓':''}</b>${n}<small>${progress.best[i]?`最好成绩 ${progress.best[i]} 秒`:'还没有一起走出去'}</small></button>`).join('')+'</div><button class="primary" id="randomLevel">无尽大聪明模式 ↗</button>');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{resumeAfterModal=false;closeModal();start(+b.dataset.level);});$('randomLevel').onclick=()=>{resumeAfterModal=false;closeModal();start(8,Math.floor(Math.random()*9999)+1);};};
$('home').onclick=e=>{e.preventDefault();demo=null;$('demoBanner').classList.add('hidden');state='menu';keys={};$('startScreen').classList.remove('hidden');$('pauseScreen').classList.add('hidden');$('winScreen').classList.add('hidden');};
// Small debug surface allows deterministic engine and level verification without changing gameplay.
window.gameApp={get game(){return game;},get state(){return state;},start,get spritesLoaded(){return loaded;}};
requestAnimationFrame(frame);

function takeover(){demo=null;keys={};$('demoBanner').classList.add('hidden');toast('交给你了！机关状态保留，接着走。');canvas.focus({preventScroll:true});}
$('demoBtn').onclick=()=>{const index=game.level.index,seed=game.level.seed;start(index,seed);game.wasDemo=true;demo=createDemonstration(game);demoSlowFrame=0;$('demoBanner').classList.remove('hidden');$('demoStep').textContent='从头示范这一关，随时可以接管。';toast('高玩已接管 · 当前关卡从头演示');};
$('takeoverBtn').onclick=takeover;
